### ISSUE TITLE
Would this scraper extract an epigraph marked as epigraph > cit > quote > hi? 

### ISSUE THREAD

**Issue by JonathanReeve** [aaronmendonplasek/19th_C._novel_scraper#7]
As you know, I'm marking up [this Joyce novel](https://github.com/JonathanReeve/corpus-joyce-portrait-TEI), and I'm trying to mark up the beginning epigraph as richly as possible. Here's what I have so far: 

``` xml
<epigraph xml:lang="la">
    <cit> 
        <quote><hi rend="italic">Et ignotas animum dimittit in artes.</hi></quote>
        <bibl>- Ovid, <hi rend="italic">Metamorphoses</hi>, VIII, 188</bibl>
    </cit> 
</epigraph>
```

Two questions: 
1. Would you mark up this epigraph like this, or another way? Since you've seen a lot of epigraphs marked up in TEI, I'm interested to know whether there might be a better way of doing this. 
2. Would this scraper extract this epigraph if I marked it up like this?

**Comment by aaronplasek** [comment]
Yeah, this is very similar to the TEI files I have. However, instead of just using the <bibl> tag, you might also want to use nested <author> and <title> tags. That way you can automatically extract these features with very little additional code. For example:
```xml
<epigraph>
 <cit>
                  <quote>
                     <lg type="verse" org="uniform" sample="complete" part="N">
                        <l rend="indent" part="N">I will recal</l>
                        <l part="N">Some facts of ancient date: he must remember</l>
                        <l part="N">When on Cithaeron we together fed</l>
                        <l part="N">Our several flocks.</l>
                     </lg>
                  </quote>
                  <bibl default="false">
                     <author>
                        <hi rend="smallcaps">Sophoc. Oedip. Tyran</hi>.</author>
                  </bibl>
               </cit>
            </epigraph>
```

**Comment by aaronplasek** [comment]
also, weird that md doesn't render for me

**Comment by aaronplasek** [comment]
And, yes, the scraper would definitely get epigraphs formatted in the way you suggest. The scraper should be general enough such that it should retrieve any epigraph-tagged content from any xml file (i.e., regardless of the xml structure of the file). (This is one bonus of using beautiful soup, as I understand it.)

**Comment by JonathanReeve** [comment]
Awesome. I'll make these changes to my `<epigraph>` tag soon. Thanks for that!
